let mydate =new Date()
//console.log(mydate.toString())
//console.log(mydate.toLocaleString())
//console.log(typeof mydate)
let mycreateddate = new Date(2023,0,23)
console.log(mycreateddate.toString())
let mycreateddates = new Date("2023-01-14")
console.log(mycreateddate.toString())
let mytimestamp=Date.now()
console.log(mytimestamp)
console.log(mycreateddate.getTime())
console.log(Date.now()/1000)